version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Puerto para la comunicación AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión de RabbitMQ

  receive:
    build: .
    depends_on:
      - rabbitmq
    restart: always
    links:
      - rabbitmq
    command: node ./API-Logs/rabbitmqReceive.js

  app:
    build: .
    depends_on:
      - mysqldb
      - rabbitmq
    links:
      - mysqldb
      - rabbitmq
    ports:
      - "3000:3000"
