version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"
    restart: always

  profiles_mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE_PROFILES=$MYSQLDB_DATABASE_PROFILES
    ports:
      - "$MYSQLDB_PROFILES_LOCAL_PORT:$MYSQLDB_PROFILES_DOCKER_PORT"
    volumes:
      - ./API-Profiles/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  mongoDB:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "$MONGODB_PORT:$MONGODB_PORT"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Puerto para la comunicación AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión de RabbitMQ
    restart: always

  receive:
    build: .
    depends_on:
      - rabbitmq
    restart: always
    links:
      - rabbitmq
    command: node ./API-Logs/rabbitmqReceive.js

  api_logs:
    build:
      context: .
      dockerfile: ./API-Logs/Dockerfile
    ports:
      - "$PORT_LOGS:$PORT_LOGS"
    depends_on:
      - mongoDB
      - rabbitmq
    restart: always

  app:
    build: .
    depends_on:
      - mysqldb
      - rabbitmq
    restart: always
    links:
      - mysqldb
      - rabbitmq
    ports:
      - "3000:3000"
    restart: always
  
  api_profiles:
    build:
      context: .
      dockerfile: ./API-Profiles/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - profiles_mysqldb
      - app
      - rabbitmq
    restart: always

  gateway_api:
    build:
      context: ./API-Gateway
    ports:
      - "5000:5000"
    depends_on:
      - app
    environment:
      RABBITMQ_SERVICE: rabbitmq
      SERVICE_NAME: gateway_api
      USERS_API_URL: "http://app:3000"
      PROFILES_API_URL: "http://api_profiles:4000"
    restart: always
   

  api_health:
    build:
      context: .
      dockerfile: ./API-Health/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - app
      - api_logs
      - api_profiles
    restart: always

volumes:
  mongodb_data:
