version: '3.8'

services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "$MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT"

  mongoDB:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "$MONGODB_PORT:$MONGODB_PORT"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD

  rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"  # Puerto para la comunicación AMQP
      - "15672:15672"  # Puerto para la interfaz de gestión de RabbitMQ

  receive:
    build: .
    depends_on:
      - rabbitmq
    restart: always
    links:
      - rabbitmq
    command: node ./API-Logs/rabbitmqReceive.js

  api_logs:
    build:
      context: .
      dockerfile: ./API-Logs/Dockerfile
    ports:
      - "$PORT_LOGS:$PORT_LOGS"
    depends_on:
      - mongoDB
      - rabbitmq

  app:
    build: .
    depends_on:
      - mysqldb
      - rabbitmq
    links:
      - mysqldb
      - rabbitmq
    ports:
      - "3000:3000"

volumes:
  mongodb_data:
