# Base image
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY ./API-Health/requirements.txt .

# Copiar los archivos necesarios al contenedor
COPY . .

# Instalar dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto 8000
EXPOSE 8000

# Comando de ejecución
CMD ["python", "./API-Health/health.py"]



